2025-03-27 19:49:34,724 ERROR: Exception on /timer_status [GET] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 47, in timer_status
    timer.end_time = timer.end_time.replace(tzinfo=timezone.utc)
                    ^^^^^^^^^^^^^^^^^^^^
TypeError: can't subtract offset-naive and offset-aware datetimes
2025-03-27 19:49:36,803 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-27 19:49:40,828 ERROR: Exception on /results [GET] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 84, in results
    return render_template("results.html", title="Results")
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 737, in update_template_context
    context.update(func())
                   ~~~~^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 15, in inject_timer_status
    seconds_left = int((timer.end_time - now).total_seconds())
                        ~~~~~~~~~~~~~~~^~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
2025-03-27 19:49:41,946 ERROR: Exception on /results [GET] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 84, in results
    return render_template("results.html", title="Results")
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 737, in update_template_context
    context.update(func())
                   ~~~~^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 15, in inject_timer_status
    seconds_left = int((timer.end_time - now).total_seconds())
                        ~~~~~~~~~~~~~~~^~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
2025-03-27 19:51:50,528 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-27 20:22:39,562 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-27 20:22:41,030 ERROR: Exception on /results [GET] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 88, in results
    crews = sorted(crews, key=Crew.balance)
TypeError: 'InstrumentedAttribute' object is not callable
2025-03-27 20:23:52,370 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-27 20:46:07,536 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-27 20:46:10,483 ERROR: Exception on /results [GET] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 89, in results
    return render_template("results.html", title="Results", crews=crews)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/equist/.local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/equist/.local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/equist/Programming/ports-game/ports/src/templates/results.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/equist/Programming/ports-game/ports/src/templates/base.html", line 92, in top-level template code
    href="{{ url_for('Services') }}"
    
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/equist/.local/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'Services'. Did you mean 'services' instead?
2025-03-27 20:46:24,239 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-27 20:46:48,753 ERROR: Exception on /start_timer [POST] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 30, in start_timer
    end_time = now + timedelta(minutes=minutes)
               ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: date value out of range
